print("Let's play Mad Libs for Homework 1 \nType one word responses to the following: \n")
proper_name= input("proper_name ==> ")
print(proper_name)
adjective = input("adjective ==> ")
print(adjective)
noun = input("noun ==> ")
print(noun)
verb = input("verb ==> ")
print(verb)
verb_2 = input("verb ==> ")
print(verb_2)
noun_2 = input("noun ==> ")
print(noun_2)
emotion = input("emotion ==> ")
print(emotion)
verb_3 = input("verb ==> ")
print(verb_3)
noun_3 = input("noun ==> ")
print(noun_3)
season = input("season ==> ")
print(season)
adjective_2 = input("adjective ==> ")
print(adjective_2)
emotion_2 = input("emotion ==> ")
print(emotion_2)
team_name = input("team-name ==> ")
print(team_name)
noun_4 = input("noun ==> ")
print(noun_4)
adjective_3 = input("adjective ==> ")
print(adjective_3, "\n")
out_str=("Here is your Mad Lib...\n\nGood morning {}!\n\n\tThis will be a/an {} {}! Are you {} forward to it?\n\tYou will {} a lot of {} and feel {} when you do.\n\tIf you do not, you will {} this {}.\n\n\tThis {} was {}. Were you {} when {} won\n\tthe {}?\n\n\tHave a/an {} day!").format(proper_name, adjective,noun,verb,verb_2, noun_2, emotion, verb_3, noun_3, season, adjective_2, emotion_2, team_name,noun_4 , adjective_3)
#just need one string w/ variables defined by user inputs 
print(out_str)